<a href="https://colab.research.google.com/github/bariskucuk1999/data-science-notes/blob/main/DeepLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
veriler=pd.read_csv("Churn_Modelling.txt")
veriler

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [ ]:
#veri ön işleme
X=veriler.iloc[:,3:13].values
Y=veriler.iloc[:,13].values
#encoding:kategorik->nümerik
from sklearn import preprocessing
le=preprocessing.LabelEncoder()
X[:,1]=le.fit_transform(X[:,1]) #geography column
le2=preprocessing.LabelEncoder()
X[:,2]=le2.fit_transform(X[:,2]) #gender column
#one hot encoding
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ohe=ColumnTransformer([("ohe",OneHotEncoder(dtype=float),[1])],remainder="passthrough")
X=ohe.fit_transform(X)
X=X[:,1:]
X

array([[0.0, 0.0, 619, ..., 1, 1, 101348.88],
       [0.0, 1.0, 608, ..., 0, 1, 112542.58],
       [0.0, 0.0, 502, ..., 1, 0, 113931.57],
       ...,
       [0.0, 0.0, 709, ..., 0, 1, 42085.58],
       [1.0, 0.0, 772, ..., 1, 0, 92888.52],
       [0.0, 0.0, 792, ..., 1, 0, 38190.78]], dtype=object)

In [ ]:
X[0:5,:] #ilk 5 satırı yazdırma

array([[0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
       [0.0, 1.0, 608, 0, 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [0.0, 0.0, 502, 0, 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [0.0, 0.0, 699, 0, 39, 1, 0.0, 2, 0, 0, 93826.63],
       [0.0, 1.0, 850, 0, 43, 2, 125510.82, 1, 1, 1, 79084.1]],
      dtype=object)

In [ ]:
X[:,8:10] #8 ve 9. sütunları yazdırma

array([[1, 1],
       [0, 1],
       [1, 0],
       ...,
       [0, 1],
       [1, 0],
       [1, 0]], dtype=object)

In [ ]:
#verilerin eğitim ve test için bölünmesi
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.33,random_state=0)
#verilerin ölçeklenmesi
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(x_train) #normalize edildi
X_test=sc.fit_transform(x_test)
X_train

array([[-0.56953701, -0.57436296, -1.78451879, ..., -1.56299709,
        -1.03339307,  1.0890591 ],
       [-0.56953701, -0.57436296,  1.47401668, ...,  0.63979645,
         0.967686  , -0.4551902 ],
       [-0.56953701, -0.57436296, -0.82854466, ..., -1.56299709,
         0.967686  , -0.65446947],
       ...,
       [-0.56953701, -0.57436296,  0.89837634, ...,  0.63979645,
        -1.03339307,  1.40745917],
       [-0.56953701,  1.74105933, -0.62295883, ...,  0.63979645,
         0.967686  ,  0.83939459],
       [ 1.75581215, -0.57436296, -0.2837422 , ...,  0.63979645,
        -1.03339307,  0.31973777]])

**Müşteri Kayıp Analizi**

In [ ]:
#yapay sinir ağları
import keras
from keras.models import Sequential
from keras.layers import Dense
classifier=Sequential() #yapay sinir ağı oluşturuldu
classifier.add(Dense(6,kernel_initializer="uniform",activation="relu",input_dim=11)) #giriş katmanı(11 bağımsız değişken için)
#input_dim->yapay sinir ağı giriş katmanındaki veri sayısı
#6 nörondan oluşan bir gizli katman
classifier.add(Dense(6,kernel_initializer="uniform",activation="relu")) #ikinci gizli katmanı ekleme

In [ ]:
classifier.add(Dense(1,kernel_initializer="uniform",activation="sigmoid")) #çıkış katmanı
classifier.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])
classifier.fit(X_train,y_train,epochs=50) #x'den y'yi öğrenme(bağımsız değişkenlerden bağımlı değişkeni öğrenme)
y_pred=classifier.predict(X_test)
y_pred

Epoch 1/50
210/210 [==============================] - 1s 1ms/step - loss: 0.5793 - accuracy: 0.7978
Epoch 2/50
210/210 [==============================] - 0s 2ms/step - loss: 0.4383 - accuracy: 0.7979
Epoch 3/50
210/210 [==============================] - 0s 1ms/step - loss: 0.4313 - accuracy: 0.7979
Epoch 4/50
210/210 [==============================] - 0s 1ms/step - loss: 0.4281 - accuracy: 0.7979
Epoch 5/50
210/210 [==============================] - 0s 1ms/step - loss: 0.4261 - accuracy: 0.7979
Epoch 6/50
210/210 [==============================] - 0s 1ms/step - loss: 0.4239 - accuracy: 0.7979
Epoch 7/50
210/210 [==============================] - 0s 1ms/step - loss: 0.4211 - accuracy: 0.7979
Epoch 8/50
210/210 [==============================] - 0s 1ms/step - loss: 0.4191 - accuracy: 0.7979
Epoch 9/50
210/210 [==============================] - 0s 1ms/step - loss: 0.4175 - accuracy: 0.8173
Epoch 10/50
210/210 [==============================] - 0s 1ms/step - loss: 0.4163 - accuracy: 0.8196

array([[0.2538057 ],
       [0.3448224 ],
       [0.17514157],
       ...,
       [0.2530751 ],
       [0.55892295],
       [0.02522138]], dtype=float32)

In [ ]:
y_pred=(y_pred>0.5) #true olanları döndürme
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
#gerçek veriden elde edilen actual datalar ile elde ettiğimiz y_pred değerlerini karşılaştırma
cm

array([[2551,   66],
       [ 466,  217]])