<a href="https://colab.research.google.com/github/bariskucuk1999/data-science-notes/blob/main/PCA%26LDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**PCA(Principal Component Analysis)**
*   Boyut dönüştürme/indirgeme, gözetimsiz(sınıflar arası ayrım önemsiz)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
veriler=pd.read_csv("Wine.txt")
X=veriler.iloc[:,0:13].values
y=veriler.iloc[:,13].values
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2,random_state=0)
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)
#boyut indirgeme(daha az sayıda column'a indirgeme)
from sklearn.decomposition import PCA #pca dönüşümü
pca=PCA(n_components=2)
X_train2=pca.fit_transform(X_train) #fit_transform()->hem eğitim hem uygulama
X_train2 #2 boyuta indirgendi

array([[-2.17884511e+00, -1.07218467e+00],
       [-1.80819239e+00,  1.57822344e+00],
       [ 1.09829474e+00,  2.22124345e+00],
       [-2.55584748e+00, -1.66210369e+00],
       [ 1.85698063e+00,  2.41573166e-01],
       [ 2.58288576e+00, -1.37668170e+00],
       [ 8.72876119e-01,  2.25618512e+00],
       [-4.18384029e-01,  2.35415681e+00],
       [-3.04977245e-01,  2.27659433e+00],
       [ 2.14082532e+00, -1.10052871e+00],
       [-2.98136465e+00, -2.47159183e-01],
       [ 1.96188242e+00,  1.25407738e+00],
       [-2.16177795e+00, -9.75966550e-01],
       [ 2.21976084e+00, -2.39507167e+00],
       [-2.30179529e+00, -2.05791962e-01],
       [-3.00953827e+00, -2.79141212e-01],
       [ 2.63443473e+00, -8.68313119e-01],
       [-1.09219965e+00, -3.53906625e+00],
       [ 2.62578435e+00, -2.96852840e-03],
       [ 1.98077342e-01,  2.29193443e+00],
       [-2.67442753e+00, -2.58800132e+00],
       [-2.54763698e+00, -4.52703891e-01],
       [ 1.77416736e+00,  8.43586940e-01],
       [-2.

In [ ]:
X_test2=pca.transform(X_test) #eğitilmiş veriyi transform etme
X_test2

array([[ 1.82267126, -0.98555382],
       [-3.02467018, -2.12103337],
       [ 1.8586049 ,  1.76532767],
       [ 2.1400017 , -1.34515879],
       [-0.67570992,  0.51599476],
       [ 0.87600011, -0.28334183],
       [ 1.65176773, -1.45860584],
       [-3.65277147, -0.85391504],
       [-0.54236534,  2.13884339],
       [-1.58795634,  2.10923292],
       [-2.69887248, -0.28431801],
       [-4.68942114, -0.64329665],
       [ 2.61500162, -2.16894005],
       [ 2.00106227,  1.27020865],
       [-2.69163444, -2.0781359 ],
       [ 0.63121666,  3.33314621],
       [ 1.37769888, -1.5097767 ],
       [ 3.04381974, -2.59877541],
       [-2.27499823,  0.7882717 ],
       [ 2.61172875, -0.76374434],
       [ 2.12402525,  1.61748275],
       [ 0.77664846, -0.0478164 ],
       [ 0.6309387 , -0.81736194],
       [ 0.18524679,  2.1120778 ],
       [-1.99008536,  1.47174605],
       [-0.51123127,  1.93593587],
       [-0.26029176,  1.14774401],
       [-1.07334931,  2.27657786],
       [-1.69447265,

In [ ]:
#lojistik regresyon üzerinden sınıflandırma yapmak istersek;
#pca dönüşümünden önce gelen Logistic Regression
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=0)
classifier.fit(X_train,y_train) #pca'dan çıkan bağımsız değişkenleri alıp bundan y_train'i öğrenme
#pca dönüşümünden sonra gelen Logistic Regression
classifier2=LogisticRegression(random_state=0)
classifier2.fit(X_train2,y_train)
#tahminler
y_pred=classifier.predict(X_test)
y_pred2=classifier2.predict(X_test2)
from sklearn.metrics import confusion_matrix
#actual/pca olmadan çıkan sonuç
print("Actual/Without PCA")
cm=confusion_matrix(y_test,y_pred)
print(cm)
#actual/pca sonrası çıkan sonuç
print("Actual/After PCA")
cm2=confusion_matrix(y_pred2,y_pred)
print(cm2)
#pca sonrası/pca öncesi
print("After PCA/Before PCA")
cm3=confusion_matrix(y_test,y_pred2)
print(cm3)

Actual/Without PCA
[[14  0  0]
 [ 0 15  1]
 [ 0  0  6]]
Actual/After PCA
[[14  1  0]
 [ 0 14  1]
 [ 0  0  6]]
After PCA/Before PCA
[[14  0  0]
 [ 1 15  0]
 [ 0  0  6]]


**LDA(Linear Discriminant Analysis)**
*   Boyut dönüştürme/indirgeme, gözetimli(sınıflar arası ayrım önemli)
*   Sınıflar arası farkı maximize etme




In [ ]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda=LDA(n_components=2)
X_train_lda = lda.fit_transform(X_train,y_train) #lda'nın çalışması için sınıfları öğrenmesi gerekli
#bu yüzden fit_transform() işlemine pca'dan farklı olarak y_train'i ekledik
X_train_lda

array([[ 3.57315552,  1.94018924],
       [ 0.85475898, -2.08182977],
       [ 0.62173655, -3.06234453],
       [ 4.80786412,  2.00638739],
       [-3.8579759 ,  0.14987256],
       [-3.59455458,  1.24961706],
       [-0.53772906, -3.0852704 ],
       [ 0.04058577, -2.47312446],
       [ 0.99835348, -3.36989668],
       [-3.74095658,  1.94844242],
       [ 3.76035226,  0.82126218],
       [-0.15106412, -1.86820292],
       [ 3.62762899,  2.05460026],
       [-3.94229781,  2.80328429],
       [ 3.33429017,  0.73627798],
       [ 3.90206871,  1.03276135],
       [-3.55835472,  0.18783108],
       [ 5.63175281,  2.40524214],
       [-5.56217254,  0.85694946],
       [ 0.23296188, -3.94615581],
       [ 5.03141997,  3.23313754],
       [ 3.52861651,  0.94605778],
       [-1.17815662, -2.17294825],
       [ 3.58320131,  0.67947364],
       [ 5.21649905,  2.41090952],
       [-3.01647841,  1.24411621],
       [ 1.86178658, -0.47484926],
       [ 3.93816398, -0.2204059 ],
       [-1.0836235 ,

In [ ]:
X_test_lda=lda.transform(X_test)
X_test_lda

array([[-2.67194963,  1.52627514],
       [ 6.66437912,  2.00282595],
       [ 0.25050926, -3.16695182],
       [-0.79414999,  0.74485091],
       [ 0.69628067, -1.27356788],
       [-3.9939152 , -2.46648925],
       [-3.66445047,  2.87676686],
       [ 6.60434327,  1.08381943],
       [-0.48587173, -2.33833194],
       [ 1.31616518, -2.37285752],
       [ 3.31754992,  1.86600436],
       [ 6.0945607 ,  2.06586769],
       [-3.88620761,  3.11744393],
       [-1.619114  , -2.53685807],
       [ 5.70655945,  2.03731911],
       [-0.01522848, -4.49013781],
       [-2.87855488,  1.66458972],
       [-4.88413879,  3.74817785],
       [ 3.2467391 , -0.78471751],
       [-3.82757435,  1.72477394],
       [-1.58747477, -2.53319372],
       [-1.32596118,  0.89348738],
       [-0.73663527,  0.27162905],
       [-0.64524695, -2.43292393],
       [ 1.84161986, -0.83662412],
       [ 1.0424462 , -2.71455717],
       [-0.26815558, -2.65408508],
       [ 1.78767861, -3.46184612],
       [-0.1349005 ,

In [ ]:
#lda dönüşümünden sonra
classifier_lda=LogisticRegression(random_state=0)
classifier_lda.fit(X_train_lda,y_train)
#lda verisini tahmin etme
y_pred_lda=classifier_lda.predict(X_test_lda)
#lda sonrası/actual
print("After LDA/Actual")
cm4=confusion_matrix(y_pred,y_pred_lda)
print(cm4)

After LDA/Actual
[[14  0  0]
 [ 0 15  0]
 [ 0  1  6]]
